config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'

  resources :entries
  resources :categories do
    member do
      resources :entries
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order(name: :asc)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.order(name: :asc)
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if @categories.any? %>
<ul>
  <% @categories.each do |cat| %>
    <li><%= link_to cat.name, category_path(cat) %></li>
  <% end %>
</ul>
<% end %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<h3>Fields</h3>
<pre><%= JSON.pretty_generate(@category.fields) %></pre>

<h3>Entries</h3>
<% if @category.entries.any? %>
<ul>
  <% @category.entries.each do |entry| %>
    <li><%= link_to entry.name, entry_path(entry) %></li>
  <% end %>
</ul>
<% end %>

app/views/entries/index.html.erb
<h1>Entries</h1>

<% if @entries.any? %>
<ul>
  <% @entries.each do |entry| %>
    <li><%= link_to entry.name, entry_path(entry) %></li>
  <% end %>
</ul>
<% end %>

app/views/entries/show.html.erb
<h1>Entry: <%= @entry.name %></h1>

<p>
  Author: <%= @entry.author %><br>
  Category: <%= @entry.category&.name %>
</p>

<h3>Observations</h3>
<pre><%= JSON.pretty_generate(@entry.observations) %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails jsonb Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <%= link_to "Entries", entries_path %> | <%= link_to "Categories", categories_path %>
    </nav>
  </header>

<%= yield %>

</body>
</html>